version: '3.8'

services:
  frontend-dev:
      build:
        context: .
        dockerfile: Dockerfile
        target: builder
      ports:
        - "5173:5173"
      container_name: octopus-frontend-dev
      volumes:
        - .:/app
        - /app/node_modules
      command: npm run dev